W7_D2/music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
end

W7_D2/music/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7_D2/music/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
end

W7_D2/music/app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  # after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.check_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token 
    self.session_token ||= SecureRandom::urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64 
    self.save!
    self.session_token
  end

  def check_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

W7_D2/music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  helper_method :current_user
  helper_method :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

W7_D2/music/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end
  
  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save!
      redirect_to bands_url
    else
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(band_params)
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

W7_D2/music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
    params[:user][:email],
    params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect email/password"]
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user.id)
    end
  end

  def new
    render :new
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end

end

W7_D2/music/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)
    @user.ensure_session_token
    if @user.save!
      log_in_user!(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

W7_D2/music/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    '<input type="hidden" name="authenticity_token" value= <%=form_authenticity_token %>'.html_safe
  end

end

W7_D2/music/app/helpers/bands_helper.rb
module BandsHelper
end

W7_D2/music/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7_D2/music/app/helpers/users_helper.rb
module UsersHelper
end

W7_D2/music/app/views/bands/edit.html.erb
<h2>Edit Band Page</h2>

<form action="<%= band_url(@band) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  
  <label for="band-name">Name: </label>
  <input type="text" id="band-name" name="band[name]" value="<%= @band.name %>">
  
  <input type="submit" value="Update">
</form>

W7_D2/music/app/views/bands/index.html.erb
<h2>Bands</h2>

<ol>
  <% @bands.each do |band| %>
  <li><%= band.name %></li>
    <a href="<%= band_url(band) %>">Show band</a>
    <a href="<%= edit_band_url(band) %>">Edit band</a>
  <% end %>
</ol>

W7_D2/music/app/views/bands/new.html.erb
<h2>New Band Page</h2>

<form action="<%= bands_url %>" method="POST">
  <%= auth_token %>
  
  <label for="band_name">Name: </label>
  <input type="text" id="band_name" name="band[name]" value="<%= @band.name %>">
  
  <input type="submit">
</form>

W7_D2/music/app/views/bands/show.html.erb
<h2>Welcome to your band page, <%= @band.name %></h2>

W7_D2/music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= auth_token %>

    <% if logged_in? %>

    <form action="<%= session_url %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Logout">
    </form>

    <% else %>

      <a href="<%= new_user_url %>">Sign up</a>
      <a href="<%= new_session_url %>">Log in</a>

    <% end %>

    <%= yield %>
  </body>
</html>